class LoginLocators:
    EMAIL = "input[name='email']"
    LOGIN_BUTTON = "button[type='submit']"
    REGISTER_BUTTON = "text=Register"
    
    first_name = "input[id='customer.firstName']"
    last_name = "input[id='customer.lastName']"
    address = "input[id='customer.address.street']"
    city = "input[id='customer.address.city']"
    state = "input[id='customer.address.state']"
    zip_code = "input[id='customer.address.zipCode']"
    phone = "input[id='customer.phoneNumber']"
    ssn = "input[id='customer.ssn']"
    username = "input[id='customer.username']"
    password = "input[id='customer.password']"
    confirm_password = "input[id='repeatedPassword']"
    register = "input[value='Register']"
    accounts_overview = "text=Accounts Overview"
    account_balance_value = "//table[@id='accountTable']//b"
